[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r backend/requirements.txt",
  "npm ci",
  "npm run build"
]

[phases.build]
cmds = [
  "echo 'Frontend already built in install phase'"
]

[start]
cmd = "./start.sh"

