[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:all"

