[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "npm ci",
  "npm run build"
]

[start]
cmd = "npm run start:all"

