[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m venv venv",
  "source venv/bin/activate && pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "echo 'Backend only - no frontend build needed'"
]

[start]
cmd = "./start.sh"

