[build]
builder = "nixpacks"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
port = 8080

[env]
NODE_ENV = "production"
VITE_API_URL = "https://pulse2-production.up.railway.app"
