services:
  - type: web
    name: pulse-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn api_endpoints:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.6